' update frequence': 1
accelerator: null
accumulate_grad_batches: 1
adafactor: false
adam_epsilon: 1.0e-08
amp_backend: native
amp_level: O2
attention_dropout: null
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
benchmark: false
cache_dir: ''
check_val_every_n_epoch: 1
checkpoint: null
checkpoint_callback: true
config_name: ''
data_dir: /root/AMR-PLM/amr-seq2seq/data/AMR17-parsing
decoder_layerdrop: null
default_root_dir: null
deterministic: false
devices: null
distributed_backend: null
do_predict: true
do_train: true
dropout: null
early_stopping_patience: 15
encoder_layerdrop: null
eval_batch_size: 8
eval_beams: 5
eval_max_gen_length: 1024
fast_dev_run: false
feature_dim: 32
flush_logs_every_n_steps: 100
fp16: true
fp16_opt_level: O2
freeze_embeds: false
freeze_encoder: false
gpus: 1
gradient_clip_algorithm: norm
gradient_clip_val: 0.0
ipus: null
label_smoothing: 0.0
learning_rate: 5.0e-05
learning_rate2: 0.0005
limit_predict_batches: 1.0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
log_every_n_steps: 50
log_gpu_memory: null
logger: true
logger_name: default
lr_scheduler: linear
max_epochs: 20
max_source_length: 512
max_steps: null
max_target_length: 1024
max_time: null
max_tokens_per_batch: null
min_epochs: null
min_steps: null
model_name_or_path: facebook/bart-large
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
n_test: -1
n_train: -1
n_val: -1
no_feature: false
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 2
num_workers: 4
output_dir: /root/AMR-PLM/amr-seq2seq/outputs/AMR17-bart-large-amrparsing-baseline-lr5e-5-init-noearly-beam5-leonard-smart2-debug-amrtoken-py38torch1.8
overfit_batches: 0.0
plugins: null
precision: 32
prepare_data_per_node: true
process_position: 0
profiler: null
progress_bar_refresh_rate: null
radam: false
reload_dataloaders_every_epoch: false
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
resume_from_checkpoint: null
save_top_k: 1
seed: 42
smart_init: true
sortish_sampler: false
src_lang: ''
stochastic_weight_avg: false
sync_batchnorm: false
task: amrparsing
terminate_on_nan: false
test_max_target_length: 1024
tgt_lang: ''
tokenizer_name: null
tpu_cores: null
track_grad_norm: -1
train_batch_size: 8
truncated_bptt_steps: null
val_check_interval: 1.0
val_max_target_length: 1024
val_metric: null
warmup_steps: 0
weight_decay: 0.0
weights_save_path: null
weights_summary: top
